alert("Welcome to our Website");
var Name =prompt("What's your Name?");
alert("Hello"+Name);
var Firstname = prompt("Enter your First Name");
var Lastname = prompt("Enter your Last Name");
var fullname = (Firstname + " " + Lastname);
alert(fullname);
var hobby = prompt("What's your favouraite hobbies");
alert("Your Favouraite hobby is " + hobby +".");
 BirthYear = prompt("Enter your Birth Year");
 Currentyear = prompt("Enter the Current Year");
 age = Currentyear - BirthYear;
alert("Your age is " + age);
Number1 = prompt("Enter the first number");
Number2 = prompt("Enter the second number");
sum=Number1 * Number2;
alert("The sum is: "+sum);
//challenge
var number1 = prompt("Enter your first number");
var number2 = prompt("Enter your second number");
sum_total = number1 -number2;
differnce_total = number1 - number2;
product_total = number1 * number2;
quotient_total = number1 / number2;
remainder_total = number1 % number2;
alert("sum: " + differnce_total);
alert("differnce: " + differnce_total);
alert("product: " + product_total);
alert("quotient: " + quotient_total);
alert("remainder: " + remainder_total);


